### ISSUE TITLE
Add Now + GitHub

### ISSUE THREAD

**Issue by ericclemmons** [cdonohue/css-system#6]
https://zeit.co/github

**Comment by cdonohue** [comment]
This is complete. Although, it might not take effect until the next PR @ericclemmons .

**Comment by ericclemmons** [comment]
This is what my projects look like:
> ![screenshot_2018-10-08 build software better together](https://user-images.githubusercontent.com/15182/46647534-4aa04700-cb45-11e8-822e-4542dec9be1d.png)

**Comment by cdonohue** [comment]
My fault on this @ericclemmons . I just realized that an empty `now.json` file needs to exist.
